services:
  - type: web
    name: ai-lead-agent
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GROQ_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false